# Generated by Django 5.1 on 2024-08-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0002_reader"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reader",
        ),
    ]
